/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 例えば Apache の `DocumentRoot` ディレクティブ<https://httpd.apache.org/docs/2.4/en/mod/core.html#documentroot>に相当するディレクトリの絶対パス、または `node` ディレクトリを基準にした相対パス
 */
export type DocumentRoot = string;
export type URL = string;
export type NoName1 = string;
export type Amazonpa = string;
export type Crawler = string;
export type Diary = string;
export type Kumetatwitter = string;
export type Madokatwitter = string;

export interface NoName {
  documentRoot: DocumentRoot;
  url: URL;
  browserPath: NoName1;
  mail: EMail;
  sqlite: SQLite;
}
export interface EMail {
  smtp: string;
  user: string;
  password: string;
  port: number;
  from: string;
  to: string;
}
export interface SQLite {
  db: DBNode;
}
export interface DBNode {
  amazonpa?: Amazonpa;
  crawler?: Crawler;
  diary?: Diary;
  kumetatwitter?: Kumetatwitter;
  madokatwitter?: Madokatwitter;
}
