/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 自然言語による、人間が見て分かりやすい名前を設定する。通知メールの件名などで使用される。
 */
export type NoName = string;
export type NoName1 = string;
export type APIKey = string;
export type APIKeySecret = string;
export type AccessToken = string;
export type AccessTokenSecret = string;

export interface Twitter {
  title: NoName;
  image_dir: NoName1;
  twitter: TwitterAPI;
}
export interface TwitterAPI {
  production: NoName2;
}
export interface NoName2 {
  consumer_key: APIKey;
  consumer_secret: APIKeySecret;
  access_token?: AccessToken;
  access_token_secret?: AccessTokenSecret;
}
