/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 自然言語による、人間が見て分かりやすい名前を設定する。通知メールの件名などで使用される。
 */
export type NoName1 = string;
export type URL = string;
export type URLPOST = string;
export type NoName2 = string;
export type NoName4 = string;
export type NoName5 = string;

export interface NoName {
  title: NoName1;
  url: URL;
  urlParam: URLPOST;
  screenshotPath: NoName2;
  ready: NoName3;
}
export interface NoName3 {
  wrapSelector: NoName4;
  titleSelector: NoName5;
}
