# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'

## Build Settings

strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
