# Settings <https://pnpm.io/settings>

## Dependency Resolution

minimumReleaseAgeExclude:
  - '@types/*'
  - '@w0s/*'
trustPolicy: no-downgrade
blockExoticSubdeps: true

## Dependency Hoisting Settings

## Peer Dependency Settings

strictPeerDependencies: true

## CLI Settings

engineStrict: true

## Build Settings

strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
