/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName2 = string;
export type NoName3 = string;
export type AmazonAds = string;
export type Crawler = string;
export type Blog = string;
export type Kumetatwitter = string;
export type Thumbimage = string;

export interface NoName {
  browser: NoName1;
  mail: EMail;
  sqlite: SQLite;
}
export interface NoName1 {
  path: NoName2;
  ua: NoName3;
}
export interface EMail {
  smtp: string;
  user: string;
  password: string;
  port: number;
  from: string;
  to: string;
}
export interface SQLite {
  db: DB;
}
export interface DB {
  amazon_ads: AmazonAds;
  crawler: Crawler;
  blog: Blog;
  kumeta_twitter: Kumetatwitter;
  thumb_image: Thumbimage;
}
