/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 自然言語による、人間が見て分かりやすい名前を設定する。通知メールの件名などで使用される。
 */
export type NoName1 = string;
export type URL = string;
export type URLPOST = string;
export type NoName3 = string;
export type NoName4 = string;
export type NoName5 = string;
export type NoName7 = string;
export type NoName8 = string;
export type NoName9 = string;

export interface NoName {
  title: NoName1;
  url: URL;
  urlParam: URLPOST;
  ready: NoName2;
  notice: NoName6;
}
export interface NoName2 {
  wrapSelector: NoName3;
  titleSelector: NoName4;
  confirmButtonSelector: NoName5;
}
export interface NoName6 {
  messagePrefix: NoName7;
  messageSuffix: NoName8;
  separator: NoName9;
}
